import { Command } from 'commander'
import { writeFileSync, existsSync, mkdirSync, chmodSync } from 'node:fs'
import { join } from 'node:path'
import chalk from 'chalk'
import type { ProjectConfig } from '@emit-infra/core'

export function registerInit(program: Command): void {
  program
    .command('init <name>')
    .description('Scaffold a project config and Terraform root')
    .option('--domain <domain>', 'Project domain (e.g. myproject.com)')
    .option('--repo <repo>', 'GitHub repo in owner/repo format')
    .option('--region <region>', 'Hetzner region', 'nbg1')
    .option('--server-type <type>', 'Hetzner server type', 'cx22')
    .action((name: string, opts: { domain?: string; repo?: string; region: string; serverType: string }) => {
      const config: Partial<ProjectConfig> = {
        name,
        domain: opts.domain ?? `${name}.com`,
        region: opts.region as ProjectConfig['region'],
        serverType: opts.serverType,
        sshKeyName: 'emit-deploy',
        github: { repo: opts.repo ?? `develemit/${name}` },
      }

      const configPath = join(process.cwd(), '.emit-infra.json')
      if (existsSync(configPath)) {
        console.error(chalk.red(`Config already exists at ${configPath}`))
        process.exit(1)
      }

      writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n')
      console.log(chalk.green(`Created ${configPath}`))

      const tfDir = join(process.cwd(), 'terraform')
      if (!existsSync(tfDir)) {
        mkdirSync(tfDir, { recursive: true })
        writeFileSync(join(tfDir, 'main.tf'), buildTerraformRoot(config as ProjectConfig))
        writeFileSync(join(tfDir, 'variables.tf'), VARIABLES_TF)
        console.log(chalk.green(`Created terraform/ with main.tf and variables.tf`))
      }

      const workflowDir = join(process.cwd(), '.github', 'workflows')
      if (!existsSync(workflowDir)) mkdirSync(workflowDir, { recursive: true })
      const workflowPath = join(workflowDir, 'deploy.yml')
      if (!existsSync(workflowPath)) {
        writeFileSync(workflowPath, buildWorkflow(config as ProjectConfig))
        console.log(chalk.green(`Created .github/workflows/deploy.yml`))
      }

      const hooksDir = join(process.cwd(), '.githooks')
      if (!existsSync(hooksDir)) mkdirSync(hooksDir, { recursive: true })
      const hookPath = join(hooksDir, 'pre-commit')
      if (!existsSync(hookPath)) {
        writeFileSync(hookPath, buildPreCommitHook(config as ProjectConfig))
        chmodSync(hookPath, 0o755)
        console.log(chalk.green(`Created .githooks/pre-commit`))
      }

      console.log(chalk.cyan(`\nNext steps:`))
      console.log(`  emit-infra provision ${name}`)
      console.log(`  emit-infra configure ${name}`)
      console.log(`  emit-infra deploy ${name}`)
      console.log(`  git config core.hooksPath .githooks  # activate pre-commit hook`)
      console.log(`  Push to GitHub to trigger the deploy workflow`)
    })
}

function buildWorkflow(config: ProjectConfig): string {
  const image = `ghcr.io/${config.github.repo}`
  const appDir = config.deploy?.appDir ?? `/opt/${config.name}`

  return `name: Deploy

on:
  push:
    branches: [main]

env:
  IMAGE: ${image}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: \${{ env.IMAGE }}:latest,\${{ env.IMAGE }}:\${{ github.sha }}
          build-args: |
            BUILD_NUMBER=\${{ github.run_number }}
          labels: |
            build.number=\${{ github.run_number }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: \${{ secrets.SERVER_IP }}
          username: root
          key: \${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${appDir}
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
            echo "\${{ github.run_number }}" > ${appDir}/.deployed-version
`
}

function buildPreCommitHook(config: ProjectConfig): string {
  const tag = `${config.name}:pre-commit-check`
  return `#!/usr/bin/env bash
set -euo pipefail

echo "pre-commit: running checks on affected projects..."
pnpm nx affected -t check:all:e2e --base=HEAD

echo "pre-commit: verifying Docker build..."
TMPLOG=$(mktemp)
if ! docker build --build-arg BUILD_NUMBER=0 -t ${tag} . > "$TMPLOG" 2>&1; then
  cat "$TMPLOG"
  rm -f "$TMPLOG"
  echo "pre-commit: Docker build failed. Fix the above errors before committing."
  exit 1
fi
rm -f "$TMPLOG"
docker rmi ${tag} > /dev/null 2>&1 || true
echo "pre-commit: all checks passed."
`
}

// backend.tf is generated by `emit-infra setup` (remote state via R2) — do not create it here
function buildTerraformRoot(config: ProjectConfig): string {
  return `terraform {
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "~> 1.48"
    }
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
  }
}

module "server" {
  source      = "github.com/develemit/emit-infra//terraform/modules/hetzner-server?ref=main"
  name        = "${config.name}"
  server_type = "${config.serverType}"
  location    = "${config.region}"
  ssh_key_name = "${config.sshKeyName}"
}

module "dns" {
  source     = "github.com/develemit/emit-infra//terraform/modules/cloudflare-dns?ref=main"
  domain     = "${config.domain}"
  server_ip  = module.server.ipv4_address
}

output "server_ip" {
  value = module.server.ipv4_address
}
`
}

const VARIABLES_TF = `variable "hcloud_token" {
  description = "Hetzner Cloud API token"
  type        = string
  sensitive   = true
}

variable "cloudflare_api_token" {
  description = "Cloudflare API token"
  type        = string
  sensitive   = true
}

variable "cloudflare_zone_id" {
  description = "Cloudflare zone ID for the project domain"
  type        = string
}
`
