---
- name: Deploy application
  hosts: all
  become: true
  gather_facts: false

  vars:
    app_dir: "/opt/{{ project_name }}"

  roles:
    - app-deploy
    - role: postgres-backup
      when: postgres_backup_bucket is defined and postgres_backup_bucket | length > 0
