services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: delta
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5442:5432'
  api:
    build:
      context: ..
    ports:
      - '4000:4000'
